# Generated by Django 3.2.6 on 2021-08-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rows',
            field=models.ManyToManyField(blank=True, null=True, to='market.OrderRow'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product'),
        ),
    ]
